### ISSUE TITLE
Document how to force redeploy of assets

### ISSUE THREAD

**Issue by TimJones** [poseidon/typhoon#107]
### Feature

Add documentation to force terraform to copy assets and start bootkube.

---

In a bare-metal environment I wanted to wipe cluster and start fresh, but with the same assets (keys, certs, etc). Simply wiping the machines and running `terraform apply` didn't cause the assets to be copied to the fresh machines.

I tried tainting the terraform modules with no success (this is my lack of experience with terraform)

```
$ terraform taint module.cluster.null_resource.copy-etcd-secrets
Failed to parse resource name: Malformed resource state key: module.cluster.null_resource.copy-etcd-secrets
$ terraform taint module.cluster.null_resource.copy-kubeconfig
Failed to parse resource name: Malformed resource state key: module.cluster.null_resource.copy-kubeconfig
```

I ended up having to delete the `terraform.tfstate` file and regenerating all assets anyway.

**Comment by dghubble** [comment]
The maintenance documentation for [bare-metal](https://typhoon.psdn.io/topics/maintenance/#bare-metal) shows the [blue-green replacement](https://typhoon.psdn.io/topics/maintenance/#upgrades) strategy for reprovisioning clusters by commenting or deleting the cluster definition and re-running `terraform apply`. The recommendation is to keep cluster definitions in your Terraform configs, until you're ready for the cluster to be deleted (along with all its associated resources).

You won't find documentation on performing partial deletions or re-using old resources because its not currently supported and not currently a goal.

It should be suitable to use the auto-generated TLS certificates for new clusters. Attempting to use old assets can cause issues and inhibits Typhoon's ability to make improvements over releases (old certs will expire, manifest changes, changes to architecture). For example, in the past we use to have a slightly different setup for etcd TLS client and peer certificates.

*Note: Avoid deleting `terraform.tfstate`. Its fine in the early stages, but as soon as there are multiple clusters or other Terraform resources, its dangerous. You may also wish to look into [remote state](https://typhoon.psdn.io/concepts/#remote-backend).

**Comment by TimJones** [comment]
Understood. That documentation is very clear!
Unfortunately I don't think I'll have enough hardware to run 2 clusters side by side any time soon. I'll have to fudge some other way to deal with in-place upgrades for the future.

**Comment by dghubble** [comment]
Sorry about that. It is definitely a tradeoff of the replacement strategy. Maybe a good opportunity to spin up a cloud cluster, if your workloads are agnostic. Though I completely understand if that's not the case.

Essentially betting the number of orgs with a single cluster will diminish over time.

**Comment by TimJones** [comment]
Yeah, this is a home-lab setup so a little more manual intervention isn't an issue, but resources are tight!
