### ISSUE TITLE
Allow TLS materials injection in Typhoon

### ISSUE THREAD

**Issue by johnmarcou** [poseidon/typhoon#108]
### Feature

Would it be possible to update the Typhoon (and on-prem) repo to accept/reflect all the `bootkube` variables please? I am talking about these [variables](https://github.com/poseidon/terraform-render-bootkube/blob/master/variables.tf) to these [ones](https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/variables.tf).

### Tradeoffs

My understanding is Typhoon = Booktube + Matchbox + CL templates.
It would be nice to be able to customise the Kubernetes deployment like when we use bootkube manually.

Some are already accepted like `pod_cidr`, `service_cidr ` and  `networking `.
In my current context, I would like to force the `ca_certificate `, `ca_key_alg ` and `ca_private_key` to keep my `kubeconfig` files static, even after update/clusters re-creation.

Thank you.

**Comment by dghubble** [comment]
As a distribution, Typhoon makes choices about the options to expose in each module. `terraform-render-bootkube` is a lower-level component not targeted at direct usage, so it has more options. Its intentional that `pod_cidr`, `service_cidr`, and `networking` are exposed, but others are not (like `etcd_servers`).

Re-using TLS materials from old clusters isn't a supported use case today. I understand its easy because you don't have to change your `kubeconfig`, but it also creates an environment where you'll forget to rotate (they expire), rely on the materials not changing, or be disappointed if there are future changes for the TLS material inputs. I'm hesitant to support anything other than the auto-generated options.

Check the upgrade/reprovision docs for the current recommendations: https://typhoon.psdn.io/topics/maintenance/#upgrades

**Comment by dghubble** [comment]
I suppose, I'd like to better understand the desire to force old TLS materials. I'd like to think about whether there are better ways to address the underlying challenge with tooling or other solutions.

**Comment by johnmarcou** [comment]
Thanks for you fast reply, as usual, and detailed answer!
I just would like to bring some arguments to this question.

I agree it's doesn't make sense to expose all the `bootkube` argument on `Typhoon`, `etcd_servers` is a good example of internal variable.

However, I think if there is enough reasons to allow "non-generated" TLS materials on bootkube, same reasons can apply to Typhoon.

Another example, if the administrator relay on an external TLS rotation system, it might be interesting for him to be able to use it at the Typhoon deployment. 

I think it might be interesting to let the infrastructure administrator to decide how he wants to manage the security, especially for development/testing/debugging environments.

My point is, since thankfully Typhoon is open-source, I can still clone/commit to adapt to my need, but I'd like to bring some argument to this TLS material question.

**Comment by dghubble** [comment]
Good points. Let's narrow the discussion to just the Kubernetes TLS variables then, since they're plausibly "special".

I think the strongest point above is the external Kubernetes TLS system. Right now, each cluster gets its own auto-generated TLS materials for `etcd`, `apiserver`, and `kubelet`. It lives in a little bubble. Admins can get those materials via Terraform outputs to configure other components if needed (uncommon). As the number of clusters within an org increases, I see the need for external components/apps that authenticate between multiple clusters (which may be maintained in different sets of Terraform configs) or between rotating clusters rising. It needs to be made concrete, but federated prometheus's across clusters or global ingress to tolerate single-cluster loss are plausible.

I can't think of many cases where the TLS materials truly must be known a-priori though. Except just because the components are maintained in different directories (sets of Terraform configs). You? For example, with a global prometheus app, I'd want a reprovision to create a new cluster and have the change in an output cause an update to the configuration of that prometheus (add new cluster). Not have them both using credentials defined elsewhere where they'll grow stale. Practically speaking, an admin couldn't decide to rotate those independently maintained TLS materials as a `terraform apply` anyway, not without recreating the cluster.

On other points, I don't quite agree:

> for development/testing/debugging environments

I don't want to build features with the mindset of optimizing for various environments, its too much scope. Typhoon just has one flavor right now, production.

>  This is not only for humans, but for automated processing.... So each Typhoon blue-green re-deployment... force us to contact the service users to re-push kubeconfig keys to their job submitter systems.

This still sounds to me like you're aiming to set TLS materials upfront to reduce the frequency of contacting service users about rotation. Still seems like a human/process kinda problem, but its an opinion. I'd encourage having a way to push the new credentials (from Terraform output) to the system automatically so its a non-issue. 

A useful action item for now:

[ ] Review module outputs to ensure generated TLS materials are made available

**Comment by dghubble** [comment]
In fairness, there are plenty of variables that can't be altered and take effect on a live cluster. Variables like `worker_count` are safe for managing the number of workers, but others like `pod_cidr` can't be used to shift how an existing cluster allocates pod IPs.

So if the Kubernetes TLS variables are added, the use-case isn't TLS rotation systems either. It would be for general TLS systems for some use-case where the materials must be known beforehand, rather than from outputs.

**Comment by johnmarcou** [comment]
Thank you again for you detailed answer.

> Maybe have a way to push the new credentials (from Terraform output) to the system automatically so its a non-issue.

I gonna investigate more about your recommandation.
