### ISSUE TITLE
Add tags to bootstrap module

### ISSUE THREAD

**Issue by aw1cks** [poseidon/typhoon#1094]
It would be really useful if there were git tags on the bootstrap module to track its version - I can see there are some but only for the older versions. It looks like the same goes for the module in the Terraform registry - the last version uploaded there (1.16) corresponds with the last tag in the git repo.

**Comment by dghubble** [comment]
https://github.com/poseidon/terraform-render-bootstrap is a low-level subcomponent of Typhoon. Its used in Typhoon via SHA and Typhoon releases are tagged later, once clusters have all been tested for a while. Its not neccessary to then go back and tag terraform-render-bootstrap with a release tag and update that in Typhoon. Just extra work without apparent benefit to the project.

**Comment by aw1cks** [comment]
That does make sense. What would be your recommendations for tracking this, if I wanted to implement my own module on an unsupported platform? If I track HEAD, I'm assuming there's no guarantee about compatibility.

**Comment by dghubble** [comment]
Using the module via Git `source` lets you choose a SHA or a branch (e.g. master) https://www.terraform.io/language/modules/sources#selecting-a-revision. So you could choose SHAs and update them from time to time. Correct, no guarantees since Typhoon is the main project with releases, testing, CHANGELOG, etc.
