### ISSUE TITLE
ASG's for Controllers

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#128]
Is there some reason that the AWS controllers can't be in an auto scaling group?  

I ask because I'd like to convert the Classic Load Balancers to NLB's to allow for the passthru of websockets at the very least, and the only way that I can see to associate the instances to the targetgroup is via an ASG.

It seems sensible that the controllers should be able to heal themselves if they get blown away, I'm just not sure if any problems might manifest themselves because of this.

If I get it working I'll feed back a PR.

Cheers,
Paul.

**Comment by dghubble** [comment]
If you review the history, you'll find there is a reason #35. The use of controller instances is intentional.

The etcd cluster backing a Kubernetes cluster is stateful. Full stop. No getting around it. Typhoon clusters run etcd peers across "controllers". Controllers are considered stateful because of the etcd data they contain, its not appropriate to use an ASG as a result, and the number of controllers should be selected upfront. If an etcd quorum loss occurs, instances are left intact so you can follow the official etcd [recovery](https://coreos.com/etcd/docs/latest/op-guide/recovery.html) procedures.

At the foundational level, etcd doesn't endorse running etcd in ASGs. In naive implementations, replacement means data loss. A number of clever projects/attempts have been made over the years and some non-CoreOS projects do it anyway with varying degrees of safety. But officially, recovery is something best left to an admin.

There were alternative Kubernetes designs, such as running dedicated etcd instances to allow Kubernetes controllers to be in ASGs. This just moves the problem. The etcd instances become the stateful ones, can't be in an ASG, and their number must be selected upfront. Except now the architecture is more complex, you pay for VMs that just run the etcd process, and recovery is still the same. Plus if you need to scale the control plane you usually also need to scale the etcd data plan so it doesn't really solve the scale problem. If you're interested in that design, you can look at Tectonic where we chose it for enterprisey reasons.

Overall, I understand the instinct is to put everything in auto-scaling groups (AWS) or managed instance groups (GCP) and hope it auto-heals. But here I think its harmful.

**Comment by dghubble** [comment]
Switching from ELBs to NLBs is a separate desire and has merit. I agree that part is a good goal.

**Comment by dghubble** [comment]
Openning #130

**Comment by pms1969** [comment]
OK.  I'll investigate how to work this around for the controllers.  The workers a pretty easy.
