### ISSUE TITLE
deployment fails using coreos and flatcart , ignition profile is corrupted

### ISSUE THREAD

**Issue by strelok899** [poseidon/typhoon#1369]
**Description**
after doing terrafom apply the matchbox getting to start the ipxe and on the config step it stuck with 
`msg="warning parsing Ignition: " on the matchbox logs `
and the flatcart linux 
`failed to fetch config: unable to parse 2.x ignition unsupported`

same issue with coreos

**Steps to Reproduce**

just try to deploy baremetal using latest versions (2 latest)

**Expected behavior**

the pxe should bootstrap the whole cluster

**Environment**

* Platform: bare-metal
* OS: fedora-coreos, flatcar-linux - both "38.20230709.3.0" and "3510.2.6"
* Release: Typhoon version 1.27.4 and 1.27.1
* Terraform: `terraform version` v1.5.5
* Plugins: Provider plugin versions "0.5.2" and "0.13.0"

**Possible Solution**

need to check the butane creator library. something there is strange 

`/ipxe?uuid=56bdc751-1a03-4374-b8c7-60727333366a&mac=96-8d-dc-28-05-69&domain=localdomain&hostname=&serial=`

the ipxe don't have hostname and no serial which can cause the issue but i don't know typhoon code enough to clarify it

**Comment by westelh** [comment]
In my case, the matchbox on k3s causes the problem. I had deployed matchbox on k3s and it appeared to work well for serving HTTP API , except for /ignition. However, when I switched deployment method from k3s to docker, /ignition now returns the full content and typhoon works well. I hope this will help.

**Comment by dghubble** [comment]
I think @westelh is on the right track. The error message you're seeing would correspond to using an old Matchbox version that doesn't understand Ignition v3. Typhoon hasn't used Ignition 2.x since v1.24.2 in Aug 2022. 

I suspect you're running into a change to Flatcar Linux support for v1.24.2 (Aug 2022) https://github.com/poseidon/typhoon/blob/main/CHANGES.md#v1244

Since v1.24.2, Typhoon uses Butane Configs to define Flatcar Linux controller and worker nodes configurations (Ignition spec v3.3). This required Flatcar Linux 3185.0.0+ (which first added support for spec v3) and `poseidon/ct` v1.11+. On bare-metal, this also relies on Matchbox being able to render Ignition v3.3, which was added in Matchbox v0.10.0 https://github.com/poseidon/matchbox/releases/tag/v0.10.0

```
failed to fetch config: unable to parse 2.x ignition unsupported
```

It's also possible that Flatcar Linux itself will drop support for 2.x Ignition soon, but since you're seeing the error from Matchbox it would be caused by using an older Matchbox version.

**Comment by strelok899** [comment]
I installed matchbox on vm .
And I used new enough flatcar and core os as per manual and it still didn't work.
I ended just moving to Ubuntu minimal with microk8s and all working good , using cloud-init as bootstrap and not butane

**Comment by mrIncompetent** [comment]
I've hit the same issue and found the root cause (for my case, YMMV):
`poseidon/terraform-provider-ct`@v0.13.0(latest) will generate Ignition v3.4.0 configs but those aren't supported by `poseidon/matchbox`@v0.10.0 (latest).

Matchbox doesn't have validation for the write path and instead validates the ignition configs on read. Unfortunately Matchbox uses ignition v3.3.0 during read, which fails for any v3.4.0 configs.

**Comment by dghubble** [comment]
Matchbox v0.11.0 is released

**Comment by mrIncompetent** [comment]
@dghubble mind pushing the TF provider release to the terraform registry? :pray:
