### ISSUE TITLE
Service kube-dns is missing after deploy.

### ISSUE THREAD

**Issue by puppetmaster** [poseidon/typhoon#1397]
**Description**
Hello to you all and thanks for you tremendous work.

I don't know if it's typhoon related issue, so sorry if it's not.

I use the latest version available at this time 1.28.3 to deploy a bare-metal cluster with flat-car. 

I have 3 control-planes, and 7 nodes at this time.

The deployment went very well but, When I check my services the service "kube-dns" is missing. CoreDNS is deployed and all the pods are running (all 3 of them).

When I debug the DNS resolution with this [doc](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)  Nothing works (and I think it should work at this point).

I have a "coredns" service, and when I use it's IP to test name resolution it works. 

The problem is, when I create new pods on this cluster, no container as any dns resolution working and the pods have a weird nameserver configured, with an IP (10.3.0.10) with no relations with my cluster at all ...

**Steps to Reproduce**

- Deploy a bare-metal cluster v1.28.3 with flatcar linux 3510.2.0.
  - 3 control planes
  - at least 3 nodes
  - set a pod_cidr of your choosing
  - set a service_cidr of you choosing
- Follow the [documentation](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/) to debug DNS resolution.

**Expected behavior**

The DNS resolution should work by default.

**Environment**

* Platform: bare-metal
* OS: flatcar-linux  3510.2.0
* Release: v1.28.3
* Terraform: v1.5.7
* Plugins: 
  * poseidon/ct v0.11.0
  * poseidon/matchbox v0.5.2

**Possible Solution**
I don't have on yet but I'm searching very hard...

**Comment by puppetmaster** [comment]
More informations on the matter. 
If you don't set a "service_cidr" in your cluster, everything works as expected.

**Comment by dghubble** [comment]
The CoreDNS service should always have the 10th IP in the `service_cidr` (e.g. `10.3.0.0/16` becomes -> `10.3.0.10`). This has been the general convention in CoreOS associated clusters since ~2015. Kubernetes will setup Pods (except host network of course) to use that IP address in their /etc/resolv.conf. Nothing custom here.

When you don't set a `service_cidr`, 10.3.0.0/16 is used by default.

There is no longer a `kube-dns` service, it was deprecated several years ago. You may find old Kubernetes docs that still refer to it or use that old name for backwards compatibility.

**Comment by dghubble** [comment]
Your DNS Service IP is set in https://github.com/poseidon/typhoon/blob/main/bare-metal/flatcar-linux/kubernetes/worker/butane/worker.yaml#L114 and https://github.com/poseidon/typhoon/blob/main/bare-metal/flatcar-linux/kubernetes/worker/matchbox.tf#L81
