### ISSUE TITLE
Feature: Blue/Green Documentation

### ISSUE THREAD

**Issue by pms1969** [poseidon/typhoon#152]
### Feature

Blue/Green Documentation.

The Documentation already states that for cluster upgrades, a blue/green deployment model should be taken.  I'm a great believer in this model of deployment, but have no idea how this might work in a cloud kubernetes environment.  I'm sure I'm not the only one.  It would be helpful if there was some documentation on how to safely achieve this, preferably stating the following use cases:
*  migrating stateless pods; fairly simple I would imagine, although I can think of 2 different methods
* migrating stateful pods; harder, how does the state get from one cluster to the other.

### Tradeoffs
I can think of 2 ways in which to achieve the failover:
1. 2 separate clusters, and a lot of deploy 1 thing, check, deploy the next, check.
2. Join the clusters, and taint the pods in some way that means they all migrate to the new cluster; check everything is running on the new cluster and blow away the old one.

Not sure if either is what your thinking is on the subject, but it would be good to have some guidance.

**Comment by dghubble** [comment]
Did you see https://typhoon.psdn.io/topics/maintenance/#upgrades? It describes high level steps. The exact steps depend a lot on the organization, its scale and maturity, and the apps to migrate.

This might be a better topic to ask about on IRC. I don't wish to get to far into advising folks about application management. There are plenty of opinions and consultants who advise on this as their day job too.

IMO: It takes effort to design apps are agnostic to (cloud) platform. It takes even more thought to run stateful apps - have a plan in place before ever relying on those apps since clusters don't live forever. In my cases, I can either tolerate temporary unavailability or safely mirror data to a new cluster (not worried about losing financial transactions and such). This story is different for everyone.

**Comment by dghubble** [comment]
I think the existing docs provide as much guidance as I want to provide, so I'm going to close.

Of the two you described, the recommendation is closest to option 1. Concerning option 2, there is no notion of "joining" two entire clusters (incl. control plane and doing a pivot) so its not really viable. Plus part of the goal of blue-green is to not rely on an existing healthy cluster - the process for replacement, upgrade, emergency failover, etc. is identical.
