### ISSUE TITLE
Allow other KubeDNS domains than cluster.local

### ISSUE THREAD

**Issue by barakmich** [poseidon/typhoon#19]
### Feature

While `cluster.local` is a fine default for internal Kubernetes DNS names, it would be a useful option to allow arbitrary FQDNs controlled by the user.

The advantage being that, perhaps, `k8s.example.com` can be the subdomain of record for the cluster, and resolvable to all, with appropriate DNS.

As an optional variable for the various providers, allow setting `cluster_dns_fqdn` or similar

### Tradeoffs

It makes things a bit uglier.

**Comment by barakmich** [comment]
Self-assigning; I'd like to learn the Terraform

**Comment by dghubble** [comment]
I agree with the need, `*.local` isn't a great choice, but its the Kubernetes standard choice. Its plausible, though a bit messy, to change everywhere. It has been discussed in upstream projects and the main issue is that plenty of Kubernetes components and apps in the ecosystem seem to be assuming `cluster.local` so there may be unexpected issues.

**Comment by barakmich** [comment]
I've been running with this option set in the past, and no problems so far. If certain apps are assuming `cluster.local` -- well, they're just wrong. The correct one is `foo.default.svc` for in-cluster -- and you're going to need some other FQDN if we start talking about multiple clusters anyway.

With such a warning that it might break things, could it be an optional variable?

**Comment by barakmich** [comment]
Or at least, I'm a willing guinea pig

**Comment by aaronlevy** [comment]
I still wonder a bit about the use-case of changing this value beyond having a vanity domain. The IP addresses that are going to be returned for services that resolve to `cluster.local` are generally only addressable from nodes also running kube-proxy.

Really it seems like this would only be valuable if you do something like bastion hosts that run multiple kube-proxies for different clusters, or multi-cluster service IPs and/or pod IPs are all globally routable in your infrastructure. Or I'm missing some other use-cases...

**Comment by barakmich** [comment]
@aaronlevy Exactly that; routable service/pod IPs -- especially service -- available inside your internal network. To resolve the service, simply point at KubeDNS as the upstream for `k8s.location.example.com`

Especially if you have two clusters, and start thinking about cross cluster access, and arguments for federation. It's also perfectly reasonable to consider routing current subnets into your new cluster using, eg, Calico to form an AS and push routes through some nodes.

It's a crazy limitation anyway, why defend it? I could at most see an argument for /also/ accepting a `.local` the way localhost is valid, but we still assign our boxes hostnames. The cluster analogy for hostnames where "data centers are the new computers" is giving them control over ((sub)sub)domains.

Changing it for my clusters worked without a hitch BTW.

**Comment by dghubble** [comment]
The main use case in my mind is for multiple clusters co-existing on the same network and providing cluster local services (not the kind you'd expose via Ingress/WAN). When you configure routing infrastructure to forward `*.cluster.local` to 10.3.0.10, that only scales to one cluster, even if each cluster chooses an independent service IPv4 CIDR range. For example, suppose each cluster runs an internal prometheus service, which cluster's prometheus does `prometheus.monitoring.svc.cluster.local` resolve to?

Instead, its desirable each cluster use its own suffix, say `*.yavin.local` and `*.nemo.local` for the example clusters `yavin` and `nemo` mentioned in docs. The router can have separate forwarding rules to the `kube-dns` service for each cluster.

For Typhoon, I'd like to get this feature added, but I'd prefer it be done without an additional variable for someone to think about or misconfigure. It may be valuable if the name simply derives from the `cluster_name`, which is how many naming choices are made in Typhoon (e.g. we set Kubernetes API endpoint on cloud platforms to `cluster_name.dns_zone` rather than allowing it to be free-form).

**Comment by dghubble** [comment]
> The IP addresses ... generally only addressable from nodes also running kube-proxy.

I don't think this is uniformly the case. Especially on bare-metal, I tend to inform the router(s) of the service CIDR ranges of clusters so service IPs are addressable. With Calico BGP peering to the routers, one can also choose to make pods addressable as @barakmich mentioned. Maybe this clarifies the usage a bit.

**Comment by dghubble** [comment]
This was added as a feature in https://github.com/poseidon/typhoon/releases/tag/v1.8.5
