### ISSUE TITLE
ingress load balancer is unhealthy

### ISSUE THREAD

**Issue by mabushey** [poseidon/typhoon#195]
## Bug
xxx-controllers ELB is healthy, pointing to the controller node on port 443
xxx-ingress is unhealthy, pointing to 3 "xxx-worker" instances. One minor issue is the three servers are only in 2 AZ’s.

### Environment

* Platform: aws
* OS: Typhoon installs CoreOS. Running terraform from Ubuntu 16.04
* Terraform: Terraform v0.11.7
* Plugins:
+ provider.aws v1.14.1
+ provider.ct (unversioned)
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0

My config:
cluster_name = "xxx"
dns_zone     = "kube.xx.xx"
dns_zone_id  = "Z2LJ7Zxxx"
host_cidr    = "10.130.0.0/21"
network_mtu  = 8991

# configuration
ssh_authorized_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3aD82KyifzgBSADXD4l1oPjZSH336rEpvAbUjDE7MW ubuntu@bastion"
asset_dir          = "/home/ubuntu/.secrets/clusters/xxx"

# optional
worker_count = 3
worker_type  = "t2.large"

### Problem

Ingress Load Balancer does not come up to a healthy state

### Desired Behavior

worker targets marked healthy in ELB

### Steps to Reproduce
`terraform apply`

**Comment by dghubble** [comment]
Out of the box, Typhoon creates Ingress load balancing infrastructure _if_ you choose to apply the Ingress Controller addon. But Ingress Controllers aren't an essential part of Kubernetes clusters (minimalism). So it'll appear as unhealthy (and that's ok) unless you choose that you want the Nginx Ingress Controller addon (or some other of your choosing) for their features.

https://typhoon.psdn.io/addons/ingress/

**Comment by mabushey** [comment]
Awesome, I didn't realize there were addons in that repo (I'm using the real repo of terraform-aws-kubernetes). Thank you.

I'm trying to add a DNS alias but having issues as for some reason the controller LB is in terraform config, so I can work with it, but the worker LB is in a module. I don't understand why anyone would use a module in Terraform, as far as I can tell they exist solely to remove all control and cause limitations. In .terraform/modules/16537e0097c8db6941ad5871eb897d89/aws/container-linux/kubernetes/outputs.tf we have ${module.workers.ingress_dns_name}, but there is no zone output, so I can not create an alias A record as I need the elb zone_id. It never seems to work to change code in the modules, I suspect terraform either re-downloads them or uses a cached copy. I could fork the module on github and make the changes in the forked repo, but them I'm on a snowflake module that's not getting any updates. Any ideas or input why workers is going through a module or how to get the zoneid in a way that doesn't block updates?

**Comment by mabushey** [comment]
```
resource "aws_security_group_rule" "worker-appport" {
  security_group_id = "${aws_security_group.worker.id}"

  type        = "ingress"
  protocol    = "tcp"
  from_port   = 8080 
  to_port     = 8080
  cidr_blocks = ["0.0.0.0/0"]
}

data "aws_route53_zone" "default" {
  name         = "xx.xx"
}

resource "aws_route53_record" "kuard" {
  zone_id = "${I_cannot_be_accessed_because_Im_in_a_Module}"
  name    = "kguard"
  type    = "A"

  alias {
    name                   = "${module.workers.ingress_dns_name}"
    zone_id                = "${var.dns_zone_id}"
    evaluate_target_health = true
  }
}
```

**Comment by dghubble** [comment]
Closing, as there is no Typhoon bug here.

**Comment by dghubble** [comment]
Several aspects of your comment reveal some problems in your usage.

> I'm using the real repo of terraform-aws-kubernetes

Typhoon is very much the official repo. The terraform repos are subdirectory mirrors populated by robots, in order to populate https://registry.terraform.io/search?q=typhoon&verified=false. In no way are they more "real".

> I don't understand why anyone would use a module in Terraform, as far as I can tell they exist solely to remove all control and cause limitations.

Please explore Terraform modules in upstream docs. Typhoon isn't the right place to provide an introduction to these concepts. You're using a module by using Typhoon. Internal modules are also directly usable for "worker pools" for advanced use cases on AWS and GCP.

What you're doing is rather non-nonsensical. An AWS cluster provides an Ingress DNS name as an [output](https://github.com/poseidon/typhoon/blob/master/aws/container-linux/kubernetes/outputs.tf). You merely need to define a CNAME from your `app.example.com` to that DNS name. An example is even provided in https://typhoon.psdn.io/addons/ingress/#aws

```
resource "google_dns_record_set" "some-application" {
  # DNS zone name
  managed_zone = "example-zone"

  # DNS record
  name    = "app.example.com."
  type    = "CNAME"
  ttl     = 300
  rrdatas = ["${module.aws-tempest.ingress_dns_name}."]
}
```

Your use case does not warrant creating a firewall rule, creating an alias record, or creating a fork.

If you need further usage help, please ask in the IRC channel. I keep the issues reserved for bugs / features.

**Comment by mabushey** [comment]
Thanks for your response.
> Please explore Terraform modules in upstream docs.
Sounds like a good idea, Terraform is such an awesome easy to use tool that I've never read any docs on it other than as a reference for what options are availiable.

I figured that an alias would better support edge locations (probably not much of a deal as they are all within the same region) and have better TTL than a cname, but I'm not sure if that difference is even quantifiable.

Thanks again for the help. :)
