### ISSUE TITLE
RFE: make region a variable in require.tf

### ISSUE THREAD

**Issue by todd-dsm** [poseidon/typhoon#233]
Long-time fan - first time caller !

## Enhancement
trivial request to make `region` a variable in `require.tf`

From:

```bash
provider "aws" {                                                                   
  version = "~> 1.13"                                                              
}                                                                                  
```
To:

```bash
provider "aws" {                                                                   
  version = "~> 1.13"                                                              
  region = "${var.region}"                                                         
}
```                                                                                  

### Environment

* Platform: aws
* OS: container-linux
* Terraform: v0.11.7
* Plugins: NA
* Ref: Git SHA: NA

### Problem
We do a fair amount of testing in order to achieve our plans while staying current with typhoon. It would be great if it were possible to:

 * Test (fail)
 * Reset quickly: `git checkout HEAD .`
 * Test again

Add my vars file and pass them like:

```bash
terraform plan \                                                           
    -var-file="build.tfvars" \                                         
    -out=/tmp/kubes.plan 2>&1 | tee /tmp/kubes.out
```

Everything from `build.tfvars` expands except region; typhoon just keeps nagging. It's a bit exhausting after a while. 

### Desired Behavior

 1. `git clone typhoon`
 2. `cd ~/code/typhoon/aws/container-linux/kubernetes`
 3. `git clone mystuff`
4. `make tf-init && make tf-plan`

It's one line in one file. I hope it's doable.

**Comment by dghubble** [comment]
> Everything from build.tfvars expands except region; typhoon just keeps nagging.

?? Can you please what you're referring to? Expands? Nagging?

Have you seen the tutorial [here](https://typhoon.psdn.io/cl/aws/)? There should be no reason to pass in a region to the module. You define aws provider(s) in your `providers.tf` file and they're associated with a region. Each cluster definition declares the provider is uses. You can alias those however you like. You only need `terraform init`, `terraform plan`, and `terraform apply` - everything is declared in configs rather than depending on your invocation flags.

`require.tf` is for specifying minimum versions of Terraform and plugin versions. `require.tf` will be replaced once Terraform finishes work to allow modules to declare minimum module versions they depend upon.

**Comment by todd-dsm** [comment]
My bad, I was reading the [Typhoon/AWS](https://typhoon.psdn.io/cl/aws/#provider) piece a bit off-kilter. But also found the  [Terraform provider](https://www.terraform.io/docs/modules/usage.html#passing-providers-explicitly) bit that I was _not_ aware of.
