### ISSUE TITLE
[feature] abstract DNS records

### ISSUE THREAD

**Issue by hex2a** [poseidon/typhoon#280]
### Problem
currently, DNS resources/providers are hardcoded in the respective modules. (`aws_route53_record` for aws, `digitalocean_record` for digitalocean, etc)

### Feature
implement abstraction for DNS records (own module?), so that other providers (e.g. cloudflare, dyn, ..) can be used

**Comment by dghubble** [comment]
First, let's clarify some things. DNS records for you applications can be mapped to ingress controllers using any DNS provider you like already [docs](https://typhoon.psdn.io/addons/ingress/). So you're concerned about the internal implementation detail of the Kubernetes clusters - etcd DNS records pointing to each controller and the kube-apiserver DNS record resolving to controllers (via AWS NLB or GCP global LB). Of those, users can't be allowed to manage the etcd records since it would preclude taking advantage of cloud-provider specific private DNS features in the future. So the kube-apiserver record is the only _plausible_ candidate. 

There are some clear reasons these records are an internal implementation detail:

1) Logistical: DNS records required to run a cluster should be setup as part of the Typhoon module. Users cannot pass in pre-configured records as the IPs aren't yet known. DNS records can't be setup afterward based on outputs because they need to be in place to bootstrap the cluster.
2) Usability: Creating an AWS cluster should only require the AWS Terraform provider block. Same for other clouds. Optionally involving multiple providers increases confusion and burden.
3) Usability: By setting up records are part of the cluster, users don't have the option of doing it wrong.
4) Isolation: It is right that an AWS cluster should only rely on AWS components. A GCP cluster on GCP components, etc. Clusters should be self-contained. Users are unable to do things like making all their clusters across clouds rely on a shared DNS provider and that's good.
5) Complexity: Clearly more complicated if DNS records are abstract. 
4) Little benefit: DNS providers have little in the way of differentiation. Sure maybe I've got a favorite for my application records. But its fine for AWS clusters to use AWS records, GCP clusters to use GCP records, etc. Its hard to fathom a concrete benefit, let alone one that's worth the downsides. I'm sure Cloudflare would love to sell some DDoS protection or something, but its such a stretch.

Logistically, I don't know how this would be achieved and I don't think its a good goal.
