### ISSUE TITLE
[feature/bug] generate only one ignition for flatcar/online/cached

### ISSUE THREAD

**Issue by kratan** [poseidon/typhoon#281]
### Environment
bare metal, coreos, latest version

### Problem
multiple ignition files templates gets generated for flatcar, cached, and online installations, see /var/lib/matchbox/ignition/*. That takes time and bloats the config.

### Desired Behavior
only one group templates files should be generated. 

### Steps to Reproduce
terraform apply

**Comment by dghubble** [comment]
An install profile (and Ignition/ContainerLinuxConfig) (see [count](https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/profiles.tf#L96)) to define how each machine should perform its initial OS install.

Its clearest why this is required looking at say a controller or worker config, because the [data varies between machines](https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/profiles.tf#L138). Now the install phase might need per-machine variance in the future to. But the important idea is that *Matchbox can store the configs for multiple clusters globally*. There's not just one flatcar install profile. One cluster has nodes that install Flatcar alpha 1871.0.0. Another Flatcar stable 1800.7.0. Another CoreOS stable 1800.7.0. And in future, individual machines in a cluster might vary (e.g. different install disks). Its important these configs don't overwrite one another. This was considered and its why its right that we have each machine getting its own config from the beginning.

Also, the bloat concern is unfounded. Matchbox stores a variety of files and that's normal. But you can query its `/ignition?mac=MAC` endpoint to confirm each PXE booting machine is served one initial Ignition config and `/ignition?mac=MAC&os=installed` endpoint to confirm on "first boot from disk" only one Ignition config is served.
