### ISSUE TITLE
addons: ingress: have traefik as ingress controller

### ISSUE THREAD

**Issue by tasdikrahman** [poseidon/typhoon#304]
### Feature

Traefik as ingress controller. 

### Tradeoffs

Would only act on http/https and grpc and not on L4, which nginx-ingress would do for you.

**Comment by dghubble** [comment]
I'm not planning to accept additional ingress addons. Ingress Controllers should all work fine without any modifications to the Typhoon cluster, there's no need for specialized integration or to maintain manifests here. If you'd like to use Traefik, feel free to use it.

Nginx Ingress is only provided to demonstrate Ingress Controllers work on all platforms (without anything special) and because its the Ingress Controller I use and recommend to people (and therefore opt to maintain).
