### ISSUE TITLE
DO tutorial inconsistent

### ISSUE THREAD

**Issue by dbogatov** [poseidon/typhoon#316]
## Bug

On this page
https://typhoon.psdn.io/cl/digital-ocean/

It says that I need DO provider version 1.0.0 in `providers.tf`.
But in `cluster.tf` you suggest using
`source = "git::https://github.com/poseidon/typhoon//digital-ocean/container-linux/kubernetes?ref=v1.11.3"`.

It looks like the version 1.11.3 requires DO provider of version `~> 0.1.2` and thus init fails.
Removing `?ref=v1.11.3` fixed the issue for me.

**Comment by dghubble** [comment]
Published docs should be for the latest release (v1.11.3), but I had to publish them recently to fix the docs build and that included https://github.com/poseidon/typhoon/commit/db36036c81ff311fa9d131c421180f8931fe0be5. That change is needed to start using the 1.0+ plugin, but its not yet included in a tagged Typhoon release. This will be resolved when v1.12 is released and published.

By removing the `ref` you're using master (!!) btw. That's why you can now use the 1.0+ plugin.

**Comment by dbogatov** [comment]
I have figured all of that, although it took me quite some time.
And this is the point, new users should know about this issue until it is fixed in version 12.

**Comment by dghubble** [comment]
https://github.com/poseidon/typhoon/releases/tag/v1.12.1 is out and the docs reflect that.
