### ISSUE TITLE
Configure kube-controller-manager to use --horizontal-pod-autoscaler-use-rest-clients=false

### ISSUE THREAD

**Issue by elemental-lf** [poseidon/typhoon#399]
## Bug

I'm running my own fork of Typhoon which is still on Kubernetes 1.12 currently. I just stumbled over the fact that HPA wasn't working because the metrics were missing. It turned out that due the deprecation of  `heapster` `kube-controller-manager` tried to get the metrics via the `metrics-server` API by default now. I had to add `--horizontal-pod-autoscaler-use-rest-clients=false` to the `kube-controller-manager` command line to get HPA to work (again). I think that the situation with Kubernetes 1.13 is still the same, i.e. the option still exist in current Kubernetes master, so it might be useful to other users of Typhoon to add this option for the time being. I could create a PR if this is wanted.

Also see: https://github.com/kubernetes/kubernetes/issues/57673#issuecomment-354240478. And this is somewhat related to https://github.com/poseidon/typhoon/issues/368.

**Comment by dghubble** [comment]
Nice you've mentioned it for those who wish to setup Horizontal Pod Autoscaling.

Kubernetes' [Horizonal pod autoscaling](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) feature relied upon the Heapster addon and, more recently, running an aggregated API extension component. So no Typhoon cluster (or any vanilla Kubernetes cluster) has supported HPA without someone choosing to _add_ addons/extensions. Its more an extension feature rather than core Kubernetes and not part of conformance.

I'm not particularly desiring the flag. I'll ponder however. Adding it to use heapster for HPA implies some level of support for HPA when it feels out-of-scope increasingly. And it seems disingenuous when adding metrics-server isn't planned.

**Comment by elemental-lf** [comment]
I could argue  that it (probably) used to work out of the box with Typhoon in Kubernetes 1.8 when the Heapster addon *that is shipped as part of Typhoon* was installed. Which is why I've labelled it a bug. But as you already write this is more about project scope in the end. 
Will this lead to the removal of the Heapster addon and its provided metrics from Typhoon seeing that  [Heapster is retired now](https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md)?

**Comment by dghubble** [comment]
I've written about the relationship between addons and the distribution [before](https://github.com/poseidon/typhoon/pull/388): "The distribution is the cluster module itself, wheras the addons are optional manifest examples that have to be maintained in lock-step".

The change lies in Kubernetes autoscaling switching from using a heapster addon (if present) to an aggregation apiserver (if present). The heapster addon [docs](https://typhoon.psdn.io/addons/heapster/) show `kubectl apply`'ing it onto a Typhoon cluster can be used for making `kubectl top node` and `kubectl top pods` work and that's still the case today. That autoscaling piggybacked on it being present for its feature set doesn't mean HPA's features are supported. But I sympathize.

Going forward, I could stop maintaining/documenting heapster and drop the example manifests. heapster does still power `kubectl top` which was the intent originally, but its prescence does lead to these tickets. Folks could copy the manifests privately to use as desired.
