### ISSUE TITLE
[aws] kubelet, api-server extra arguments #request

### ISSUE THREAD

**Issue by dennybaa** [poseidon/typhoon#421]
Howdy,

this beautiful module is kept clean and tidy thus it's quite limited to a certain extent. I'm curious if the bellow features could be of any interest and can be considered merge candidates into the upstream:

1. Worker node instance profile IAM role?
2. Extra arguments for the kubelet container?

**Comment by dghubble** [comment]
No cloud account credentials are bound to nodes. Its by design to focus on cloud-agnostic Kubernetes usage cases and to keep a strict [security](https://typhoon.psdn.io/topics/security/) profile.

For applications that need access to account credentials, first, some cloud providers offer credentials that can be given directly to workloads via Kubernetes secrets (e.g. a GCP service accounts as a Kubernetes Secret), rather than bound to VMs. AWS is more limited. Otherwise, you'll want to explore [customization](https://typhoon.psdn.io/advanced/customization/) options.

For Kubelet arguments, if you find settings that are applicable to general clusters and useful, they can be added. But its not a goal to provide support for a free-form argument list.

**Comment by dennybaa** [comment]
I see. Regarding the first - worker instance profile iam role is not a subject to for inclusion into typhoon.
For the second `--node-labels`, `--register-with-taints` seem totally applicable @dghubble please correct me if I'm wrong.

**Comment by JordanP** [comment]
I think node labels can be set with the API, so maybe we don't need a static conf flag.

**Comment by dennybaa** [comment]
@JordanP yes obviously they can. But generally how do you suggest to set the labels of the newly created instances by of an AutoScaling group?

**Comment by JordanP** [comment]
Good point.

**Comment by dennybaa** [comment]
Also guys would you please envision the usage scenarios or maybe how this module should be properly extended (maybe anyone makes one's own fork).
Without IAM roles use in cloud platforms is very limited or I'm missing the proper usage approaches:
- no master profiles - no ability to use EBS volumes etc...
- no worker profiles - no ability to use KMS...
- lots more possible limitations

At least roles might be empty but could be allowed for user's customizations.

What am I missing?

**Comment by JordanP** [comment]
@dennybaa I understand your use case but as @dghubble said, how would you suggest we implement this in a cross-cloud compatible manner ? Cross-compatibility is a major "selling" point of Typhoon.

**Comment by dennybaa** [comment]
Yup. right. Totally agree with this one if you suppose to stick to the cross-compatibility. Let's leave alone IAM profiles I do not offer to introduce them anymore. However 
*extra arguments is a must imo*. 

How are people supposed to use this module? Out-of-the box a number of strict assumptions is taken, so that for me it seems difficult to customize typhoon. Personally I've admitted that typhoon could be a great starting point for a customizable cluster :+1:, typhoon is honestly awesome:+1:.

Though I run into many problems, probably due to a lack of experience or practical ideas how to bind these all together, I realized:
- `--cloud-provider` is still not customizable, not provided (I guess this is on the list).
- Different arguments for customizing manifests for various services such as kubelet, api-server etc should be introduced.

So this is my view, like potential users might be interested in doing their specific tuning such as enabling `--cloud-provider`, enabling feature gates etc. This obviously won't influence the default configuration "cross cloud compatibility".

When denying customization users are simply stuck without possibility to enable any features. Like it won't be even possible to enable specific feature gates to install a custom CSI plugin for example (https://github.com/digitalocean/csi-digitalocean).

Would you please clarify how users are supposed to use the module? Since there are no volumes, no ability to enable CSI (though it's told CSI ready), etc...

Please correct me if I'm missing anything, also please use cases for typhoon are welcome. For me it's difficult to envision *how I can use it without volumes*. PS. I can be really missing the "right" usage scenarios.

**Comment by dghubble** [comment]
Choices in Typhoon are rooted in years of experience designing bare-metal Kubernetes, building and leading Tectonic at CoreOS, and daily operating a network of clusters daily. Whole problem domains have risen and fallen, the space evolved, colonized by corporations. Time has provided ample lessons in how scope decisions echo across Kubernetes landscapes, architectures, and the community.

Typhoon strikes the balance among pragmatism, security, sustainability, and correctness I desire in clusters and you may too. I understand if some find it strict, but that's ok.

These may be feature checkboxes, but they're nuanced decisions. I'll try to be succint.

### Machine Roles

GCP, DO, and Azure (kinda) provide portable service account / token abstractions to interact with their services (e.g. access datastore from bare-metal). AWS does as well, but their IAM roles bound to VMs are pushed heavily (probably nothing to do with the long-term lock-in effect it creates in organizations). but here a high bar is upheld, that doesn't change on account of AWS.

In Typhoon, nodes do not get inherent account permissions. Design so that workloads _needing_ to interact with cloud services receive credentials directly. When using cloud services (e.g. bigtable), don't assume the workload is anchored to the same cloud platform.

### --cloud-provider

`--cloud-provider` is not a simple set it and done kind of option. In early Kubernetes, some providers used their clout to add code paths in-tree. There is broad consensus this was a bad idea and CCM and CSI are slowly replacing the need. The in-tree flow has specific assumptions about how hosts are configured with IAM roles and AWS tags. Allowing the flag to be set is akin to having to support the whole jumble.

### Custom arguments

Arguments that are uniformly right and proper will just be set outright and are suitable for a PR. But additional variables and especially free-form lists of extra arguments are different. As nice as they sound, these become a support burden, can create reliance on alpha features/behaviors that get canned, and can cause instability that lowers the quality bar.

If you imagine a grid, options multiply the size of the matrix of correctness. This was/is a factor in commercial distributions needing large teams to drive their ship every bell and whistle feature expansion. Typhoon has to keep this complexity low.

### CSI

I've used DigitalOcean's CSI, around v1.11, but I don't currently. It did not require custom feature gates, but their new v1.x releases now appear to rely on flags that are still alpha. That's between the authors (the features they choose to rely on) and upstream. But CSI as a principle shouldn't require modifications. 

If you need an alpha feature _now_, `kubectl edit ds apiserver -n kube-system` to add the flags at your own risk or do it in a private fork.

### Storage

There are a lot of Kubernetes [storage providers](https://kubernetes.io/docs/concepts/storage/#types-of-volumes). With various tradeoffs and stipulations.

Storage is a weak area, but I think most distros are as well. Putting data somewhere is the bare minimum consideration - there's also resilience, snapshots, backups, and how migrate it between platforms (yes). GKE/AKS/EKS enabling their disk storage also marries us to them. But we won't solve these problems today.

In my case, some applications are stateless and others are stateful. My stateful applications tend to either interact with cloud provider databases or run on-premise (several options). Not great (many similar lock-in problems) but it doesn't intrude on cluster architecture.

### Conclusion

**All that said**, its not "denying customization". The source is freely available. The "just-a-module" design is specifically made to preserve your freedom to add tweaks in a private fork and carry them. There are helpful docs on [customization](https://typhoon.psdn.io/advanced/customization/).

The idea is that someone who is able to weigh the pros/cons of a non-standard alteration (e.g. some new alpha feature, doing the work to use aws cloud provider, etc), should also be responsible for making those tweaks and carrying them on their own. If it proves to be a wise investment and the feature becomes mature and ready, Typhoon will later have it and the need for carrying a patch gone. No harm. If not, its clear what transpired. It provides a bit of a cue when something goes off the edge of the map. And keeps this project sustainable.

I hope that explains some of the reasoning.

Its the subtle cue that someone is going  the map a bit.

**Comment by dghubble** [comment]
This issue is getting into support / advice kinds of topics so I'm going to close.

But node labels and taints are in-scope for platforms that have heterogeneous nodes - platforms with worker pools that can differ and bare-metal where hardware differs. Its been in back of mind for a while, but low on the list. This can be tracked with #429

**Comment by dennybaa** [comment]
@dghubble Thank for a such detail answer!
