### ISSUE TITLE
Support for Windows nodes in 1.14

### ISSUE THREAD

**Issue by olegchorny** [poseidon/typhoon#434]
### Feature

Support of Windows nodes 

### Tradeoffs

Windows nodes are GA starting from 1.14 and it would be interesting to know if typhoon going to support them. 

Cons: Huge effort required
Pros:  Anyone who wants to leverage full .NET framework in containers will be blessed to run typhoon.

**Comment by dghubble** [comment]
If Microsoft folks stumble across this, I'd much rather their efforts go toward improving the maturity of Azure as a cloud provider. Its still considered Alpha with known shortcomings summarized [here](https://github.com/poseidon/typhoon/wiki/Errata#azure).

For Windows nodes as a feature, I'm not interested in spending time on that. Lots of more useful and interesting big areas for 2019.

**Comment by olegchorny** [comment]
@dghubble got it, thanks.

**Comment by dghubble** [comment]
Yep, sorry about that. Since its just workers, a motivated person could have their own module that's just for joining workers to a Typhoon cluster. Similar to the Azure/AWS/GCP [worker pools](https://github.com/poseidon/typhoon/tree/master/google-cloud/container-linux/kubernetes/workers), except instead of declarative provisioning at boot with Container Linux Configs, you'd need to use whatever Windows offers.

**Comment by remoe** [comment]
I've tried to run a Windows Server 2019 node in a Typhoon setup. Typhoon (terraform-render-bootkube) creates DaemonSets which are deployed on all nodes. But flanneld and kube-proxy linux container should not be deployed on Windows machines:

```node label:  kubernetes.io/os=windows```

because this binaries should run on a windows environment.

Is this something for https://github.com/poseidon/typhoon/issues/429 ?
