### ISSUE TITLE
cgroup driver option for kubelet

### ISSUE THREAD

**Issue by dongsupark** [poseidon/typhoon#480]
### Feature

As a part of [Lokomotive-Kubernetes](https://github.com/kinvolk/lokomotive-kubernetes) project, we want to allow users to choose a cgroup driver of kubelet, either `systemd` or `cgroupfs`. While Container Linux only supports `cgroupfs`, [Flatcar Linux edge](https://kinvolk.io/blog/2019/05/introducing-the-flatcar-linux-edge-channel/) enables the `systemd` cgroup driver by default. When Lokomotive-Kubernetes runs with a Flatcar edge image, it becomes possible to run kubelet with the systemd cgroup driver. We want to add such a feature not only for Lokomotive-Kubernetes, but also for Typhoon, because we should avoid divergence of the two projects as much as possible.

There can be multiple ways to do that.

### 1. Add a general variable for the kubelet parameter, like `$KUBELET_EXTRA_ARGS`.

 Doing this, we can support arbitrary kubelet options with minimal changes. Though we are aware that Typhoon does not want such a [huge possible feature matrix](https://github.com/poseidon/typhoon/issues/421#issuecomment-473450469).

### 2. Add a single variable only for cgroup driver, like `$CGROUP_DRIVER`.

 Good thing is, it will not make the supported features explode. Though we might need to add similar variables again in the future, whenever a new feature is needed.

### 3. Add a kubernetes config like `/etc/kubernetes/configure-kubelet-cgroup-driver` instead of kubelet parameters.

 This approach is already implemented in [Lokomotive-Kubernetes](https://github.com/kinvolk/lokomotive-kubernetes/commit/5f94fb5ae7e58c4a8c3022c36882604d6096d68e). Doing this, we can determine the cgroup driver at runtime, instead of specifying a cgroup driver to the kubelet.

Yesterday I had a short offline conversation about this issue with Dalton at KubeCon. He pointed to an [experimental branch](https://github.com/poseidon/typhoon/tree/flatcar-edge), which might address the cgroup driver issue. However I'm not sure the branch would be enough, because we still might need to have a way of specifying the cgroup driver.

So which of the approaches above would be the best approach for Typhoon?

**Comment by dghubble** [comment]
Typhoon Kubelet's use the `cgroupfs` cgroup driver in modules for Container Linux derivatives and the `systemd` cgroup driver in modules for Fedora Atomic (its set in the system-container image) ([docs](https://typhoon.psdn.io/architecture/operating-systems/#host-properties)). So exposing user selection of the cgroup driver shouldn't be needed and Typhoon has a precedent for setting it to match the OS's known Docker configuration.

The branch I alluded to just allows Flatcar Edge as the OS choice. Next, we can just set the Kubelet option to reflect that it should use `cgroupfs` for Flatcar Linux stable/beta/alpha, but `systemd` for Flatcar Linux edge.

To do that, I'm between either (1) internally templating the correct cgroup driver for the OS vendor or (2) a variant of the `docker info` based detection you're using in your `configure-kubelet-cgroup-driver` script. Neither seems great, but Flatcar Linux edge would be nice to have.

For (1), the oddity is just that Flarcar Linux isn't consistent across channels, so we get into which flavors need the special casing. Its tolerable. Perhaps Flatcar Linux will gravitate toward one setting?

For (2), its would be nice for the CLC to contain enough intelligence to detect the settings from docker like you're doing. But I'd like to resist having a script generating the config via heredoc if possible, since it kinda opens the door to more scripting of kubelet options (more awk). Another option might be to setup Flatcar Linux Edge users to use a droppin snippet to set the driver. 

The ideal approach would of course be for Kubelet to detect the setting eventually.

**Comment by alban** [comment]
Another argument for (2): the user might want to change Docker's configuration after provisioning to `cgroup_driver=systemd`. In that case, a reboot would just work without having to change the Kubelet config. Arguably, that's a weak argument because if the user already do manual changes to Docker, they can do manual changes to Kubelet too.

> Perhaps Flatcar Linux will gravitate toward one setting?

I would like to push Flatcar Linux toward `cgroup_driver=systemd` in order to help tools like [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget). But we've not tested enough to push that to alpha/beta/stable yet. When we do, it would be nice if Typhoon does not need patching at the same time: coordinating releases in Typhoon & Flatcar Linux seems difficult; it should be decorrelated instead.

**Comment by dghubble** [comment]
Keeping service settings aligned with vendor chosen defaults is also one of the reasons for the `kubelet-wrapper` script in the OS image. It may be simplest for the Flatcar Linux Edge `kubelet-wrapper` to have something like:

```
KUBELET_CGROUP_DRIVER="${KUBELET_CGROUP_DRIVER:-systemd}"
KUBELET_IMAGE_ARGS=${KUBELET_IMAGE_ARGS:---exec=/kubelet --cgroup-driver=${KUBELET_CGROUP_DRIVER}}
```

Then set the default according to the Docker default in the appropriate Flatcar channel and change them at your own pace / schedule. If a user does need to alter the Docker configuration, adjusting the Kubelet configuration could be done with an env variable file in a droppin.

The alternative I mention is just me doing something similar, but at the Typhoon level by using `--cgroup-driver=${KUBELET_CGROUP_DRIVER}`, adding the variable to an env file, and having flatcar edge users supply a snippet or maybe populating it for them.

**Comment by dghubble** [comment]
With #496, Typhoon will handle setting the Kubelet cgroup driver as `cgroupfs` for Container Linux + Flatcar Linux alpha/beta/stable and `systemd` for Flatcar Linux edge. Its done as a variable such that its ammenable to override by systemd droppins defined as snippets. Avoids scripting.

```
storage:
  files:
    - path: /etc/systemd/system/kubelet.service.d/10-custom.conf
      filesystem: root
      contents:
        inline: |
          [Service]
          KUBELET_CGROUP_DRIVER=systemd
```

If a user needed to alter the Docker configuration (not shown), this will let the Kubelet cgroup driver be aligned. Or if future Flatcar Linux changes the Docker configuration on the alpha/beta/stable channel(s). Although, I'd prefer Flatcar Linux do what I suggested above - in any given OS image, the default kubelet wrapper and default Docker configuration should correspond. Then this can all be dropped.

**Comment by dghubble** [comment]
Handled by  #497 and #496

**Comment by dongsupark** [comment]
Thanks! :+1:

**Comment by bugre** [comment]
> With #496, Typhoon will handle setting the Kubelet cgroup driver as `cgroupfs` for Container Linux + Flatcar Linux alpha/beta/stable and `systemd` for Flatcar Linux edge. Its done as a variable such that its ammenable to override by systemd droppins defined as snippets. Avoids scripting.
> 
> ```
> storage:
>   files:
>     - path: /etc/systemd/system/kubelet.service.d/10-custom.conf
>       filesystem: root
>       contents:
>         inline: |
>           [Service]
>           KUBELET_CGROUP_DRIVER=systemd
> ```


Hi @dghubble, 

I think the last line should be:

```
Environment=KUBELET_CGROUP_DRIVER=systemd
```
or it will not override the KUBELET_CGROUP_DRIVER environment variable defined in /etc/systemd/system/kubelet.service

If this is correct, would you mind editing your post, so that others copying the snippet (as i did) don't have to debug it to find it wasn't overriding the env variable.

for any others i found that it didn't override the variable, 
:: checking that the snippet was indeed loaded.
```
~ $ sudo systemctl status kubelet
● kubelet.service - Kubelet via Hyperkube
   Loaded: loaded (/etc/systemd/system/kubelet.service; disabled; vendor p>
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-custom.conf            <<<<<<<<<<==========
   Active: ....
```

and then, checking the environment 
```
 ~ $ sudo systemctl show --property=Environment kubelet | cat
KUBELET_CGROUP_DRIVER=systemd
```
and it should have being :
```
 ~ $ sudo systemctl show --property=Environment kubelet | cat
Environment=[unprintable] KUBELET_CGROUP_DRIVER=systemd
```

as i had changed docker to run using systemd
```
~ $ docker info |grep -i cgroup
Cgroup Driver: systemd
```

Thanks.
