### ISSUE TITLE
Add support for Packet

### ISSUE THREAD

**Issue by blixtra** [poseidon/typhoon#489]
We adapted Typhoon to run on Packet in [Lokomotive](https://github.com/kinvolk/lokomotive-kubernetes). In order to do this, we had to make a number of changes and include additional add-ons (e.g. MetalLB). Would Packet support be something that would be accepted in Typhoon if we did the work to prepare that and get it in?

**Comment by dghubble** [comment]
I've looked into [Packet.net](https://www.packet.com/) before I'm not interested in it yet. There are a number of factors:

* Packet: Use of Packet still has some warts / missing bits. Like, in your fork you've had to choose AWS Route53 for records since Packet has none. The multi-cluster balancing setup doesn't have a route toward stable, it relies on RR DNS of an external provider (contrast with bare-metal where the sky is the limit for how advanced users wanna get or DO (beta) where RR is used, but mainly due to cost cutting, LBs are present). Or firewalling just being done via the hosts. One could work around these issues, but there are also a variety of hosting platforms to choose from. I'm optimistic for Packet in the long run and really like their service, but I'm content to wait for the right time. 
* Supportability: I use and run Typhoon clusters on each supported platform. But I don't run clusters on Packet. They're too costly without the direct support of the provider. I also worry that same cost calculus skews the potential user base of a Packet variant, favoring enterprise interests. Basically, until I can justify a personal need for Typhoon on Packet, it shouldn't be added to the distro bc that directly affects quality and decision making. 
* Impl: I'd prefer to just implement new platforms afresh to know it inside and out, when the time is right. I think the minute decisions play a big role and initial working variants are straight forward enough. For example, I'd probably prefer direct integration via Matchbox and some other choices if I explored it.

So I'm currently not aiming to add support for Packet. I'm glad you guys are using it though. Packet guys are great!
