### ISSUE TITLE
K8S cluster spin up in servers already provisioned

### ISSUE THREAD

**Issue by HarithaRamesh** [poseidon/typhoon#534]
## Feature Request
Hi there, wanted to know if there is a possibility to use typhoon's terraform modules to be able to spin up a k8s cluster from inside an already provisioned vanilla coreos server? 

This is more of an inquiry than a feature request.

### Feature

We would be provisioning the servers (which will end up becoming master and worker nodes) ourselves but would be leveraging the terraform config files to create the kubernetes cluster on these nodes.

**Comment by dghubble** [comment]
If I'm reading this "provisioning the servers ourselves ... leveraging ... Terraform to create the cluster" then the answer is no.

Lots of projects let you bring arbitrary hosts in some state (various OS / cloud / platform) and run some flavor of imperative script/process to assemble hosts into a Kubernetes cluster. That's not what Typhoon aims to do. Here, modules declare clusters of Container Linux, Flatcar Linux, or Fedora CoreOS nodes on various platforms, that provision themselves using the early boot provisioning systems (immutable after first boot) of those selected operating systems. Older operating systems don't have these concepts or guarantees.

To illustrate the paradigm, imagine you need nodes running a service Z. You'd declare that you'd like nodes with service Z and boot nodes declared to run service Z, instead of booting nodes and then running a command to run service Z. Now expand that principle to a Kubernetes cluster.

**Comment by HarithaRamesh** [comment]
Alright, that makes sense. Thanks for the response!
