### ISSUE TITLE
enable feature gates

### ISSUE THREAD

**Issue by michas2** [poseidon/typhoon#545]
### Environment

* Platform: bare-metal
* OS: container-linux
* Release: v1.15.3

### Feature

Kubernetes uses [feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) to enable different features.

For example I would like to try [edgefs on rook](https://github.com/rook/rook/blob/master/Documentation/edgefs-csi.md#prerequisites), which needs some feature gates enabled.

Currently I am not aware of any easy way to enable feature gates on typhoon.

It would be great, to have an option in the terraform module to request additional features.

### Tradeoffs

I currently do not see any drawbacks. 
If you do not specify any features things work as as before.
If you *do* specify any features the corresponding options are added. - That's it.

**Comment by dghubble** [comment]
You can do feature flag testing in a fork https://typhoon.psdn.io/advanced/customization/#architecture I don't accept feature gates in mainline since it allows using alpha features as though they're supported. Requiring it be done in a fork makes it clear where responsibility lies.

https://github.com/poseidon/typhoon/issues/303#issuecomment-424275324
