### ISSUE TITLE
[terraform-render-bootstrap] store results directly in output variable, not in local file

### ISSUE THREAD

**Issue by vroad** [poseidon/typhoon#584]
### Feature

I would like terraform-render-bootstrap to store results in output variables rather than in local file.
This would allow users of the module to store generated files in remote location, or use in file provisioner (with `content` attribute).

This would be better for those reasons: 
* Predictable plan output on multiple development machines, or on CI environment. Relying on local files makes some noises in plan result, because files get generated on each machines. This is described in terraform docs. 
https://www.terraform.io/docs/providers/local/r/file.html
* Storing certs to remote object store is better for security. Even if development machine is compromised, certs are not accessible all the time if temporary credentials are used.
* Storing certs/manifests to remote object store like S3 would allow controller nodes to initialize without SSH. This would also help in making controller nodes stateless.
### Tradeoffs

~~Users of the module should write local_file resource (or object on storage like s3) by themselves.~~

No tradeoffs if you just need to create files locally.
If you want to generate files on s3 instead, you can pass null to `asset_dir` and create `aws_s3_bucket_object` by yourself, using outputs from the module.

**Comment by dghubble** [comment]
Lemme unpack the several topics you mention.

Typhoon cluster modules accept an `asset_dir` variable absoluate path where generated assets (TLS certificates, manifests, kubeconfig) should be written (e.g. typically to a local vault). Generated local assets are intended for user inspection or record-keeping. `asset_dir` is a required argument for reasons I'll describe separately, but it may someday be possible to make it optional. See #585

Given that,

* For `terraform apply`, that machine will require require access to provisioning credentials (i.e. Matchbox creds, cloud creds) and state. Use your machine (solo) or a central CI system with a durable `asset_dir` between applies. Prefer any local vault solution that works with a directory.
* Don't get hung up on adding assets in an object store, what you really want is for `asset_dir` to be optional (duplicate assets *nowhere*). The aspiration is to remove a storage location, not to introduce one.
* Secure distribution via ssh is by design. Secure copy works uniformly across bare-metal and cloud platforms. Typhoon nodes are [not endowed](https://typhoon.psdn.io/topics/security/) with credentials to access remote stores, do not run components to fetch assets, and do not rely on hosted services for bootstrap. Bootstrapping from a remote store is not a goal and would not be enabled merely by duplicating your assets to an object store. 
* Controller nodes are not at all close to being stateless. Not a goal.

**Comment by dghubble** [comment]
#585 articulates the aspect of these topics that is a goal. Going to close in favor of that.
