### ISSUE TITLE
Add AWS module support

### ISSUE THREAD

**Issue by kmarquardsen** [poseidon/typhoon#6]
## Feature Request

 Provide a Terraform Module for AWS

**Comment by kmarquardsen** [comment]
I'd like to work on this for my own use and learning

**Comment by dghubble** [comment]
A Container Linux / AWS module is planned. It'll need to live up to the standards and conventions established in Typhoon and be used in production by maintainers. There are a number of "lessons learned" that will guide this work (off the top of my head: no S3 bucket user-data, AZ spanning should be transparent, etcd matches other cloud modules, use clcs, most components are addons, no existing VPC, no private dns, no subnet picking).

Anyone is free to fork and experiment with writing a module for any platform (i.e. no claims or assignments) since this project will only support certain ones.

**Comment by kmarquardsen** [comment]
Sounds great, thanks for the quick response

**Comment by dghubble** [comment]
Let's keep this issue as the tracking issue for the feature.

**Comment by dghubble** [comment]
#18 added an alpha version. Still much I'm not happy with, but its a good start. https://typhoon.psdn.io/aws/

**Comment by dghubble** [comment]
Closing this since there is now a usable alpha, which will mature with usage and time.
