### ISSUE TITLE
CoreOS Container Linux will reach its EOL at May 26, 2020

### ISSUE THREAD

**Issue by vroad** [poseidon/typhoon#635]
### Feature

Container Linux will reach EOL at May 26, 2020, after that it will no longer receive any updates. so container-linux needs to be removed from flavors (or make flatcar-stable default at least). We still have months away from EOL though.

**Comment by dghubble** [comment]
Work on CoreOS Container Linux successors has been proceeding for years knowing Container Linux would draw to a close. Typhoon has worked to provide Fedora CoreOS and Flatcar Linux support over those years (and even had Fedora Atomic support for a bit) and on some platforms they're available for your use [today](https://twitter.com/Typhoon8s/status/1220391594550972417). 

Please consult the [README](https://github.com/poseidon/typhoon#modules) (or [docs](https://typhoon.psdn.io/#modules)) to see the support status for available OS / platform combinations, read major [announcements](https://typhoon.psdn.io/announce/), or follow https://twitter.com/typhoon8s. Note that as of February 2020, CoreOS Container Linux remains the most stable and recommended choice.

When CoreOS is EOL, those Typhoon modules will simply receive a new "discouraged" or "warning" status of some kind. The modules or options will **not** be removed.

Expanding Typhoon to successor operating systems is a broad, multi-year effort that is ongoing. Please use the linked sources for news:

* https://twitter.com/Typhoon8s
* https://typhoon.psdn.io/announce/
* https://github.com/poseidon/typhoon#modules

This issue won't be a place for updates.

**Comment by rochacon** [comment]
@dghubble should we add a disclaimer about September 1 [1] to those modules? This is when all cloud images are going to be deleted, leading to broken modules.

From the [announcement](https://coreos.com/os/eol/#timeline):

> On or after September 1, published resources related to CoreOS Container Linux will be deleted or made read-only. OS downloads will be removed, CoreUpdate servers will be shut down, and OS images will be removed from AWS, Azure, and Google Compute Engine. GitHub repositories, including the issue tracker, will become read-only. Documentation will continue to exist for as long as is practical, to aid migration to other operating systems. Existing Container Linux machines will continue running, but will no longer be able to download updates. New CoreOS Container Linux machines will not be launchable in public clouds without prior preparation.

**Comment by vroad** [comment]
Doesn't it make sense to change default value of "os_image" variable after EOL? For new users of the module, it should have sane default.

After removal of cloud images on September we have no choice but to remove coreos channels from os_image choices, and make flatcar channels the only choice.

**Comment by dghubble** [comment]
I'm aware of the various dates. I'm aware the CoreOS post has created a lot of "morbid fascination" or "world is falling" articles, tweets, and issues from commentators with differing motivations.

As usual, evolution in statuses and defaults will be made clear in the [changelog](https://github.com/poseidon/typhoon/blob/master/CHANGES.md), module [status](https://github.com/poseidon/typhoon#modules) ratings, blog [announcements](https://typhoon.psdn.io/announce/), and [tweet](https://twitter.com/Typhoon8s) announcements. Expect that in parallel with the development of new platforms, waning platforms will gradually switch to warning statuses, but be supported as long as it is practical to do so.

If you're worried for your clusters or eager to take action, start making use of the alpha modules. Otherwise, no action is needed while they stabailize, the changelog will highlight and changes in due course.
