### ISSUE TITLE
[Question]. What's the roadmap for Container linux?

### ISSUE THREAD

**Issue by balchua** [poseidon/typhoon#636]
Now that CoreOS is being sunsetted, what will be the roadmap moving forward?  
I am speaking in terms of Digitalocean.
Thanks.

**Comment by waddles** [comment]
You should be able to use Flatcar Linux as a drop-in replacement
```
os_version = "2303.3.1"
os_channel = "flatcar-stable"
```

**Comment by balchua** [comment]
This is available in digitalocean?  If yes that's awesome!

**Comment by dghubble** [comment]
Officially, Typhoon does not yet offer Kubernetes with Flatcar Linux or Fedora CoreOS on DigitalOcean.

It _is possible_ to create Typhoon clusters on DigitalOcean using either if you know the right manual steps to perform. I haven't added guides and materials for doing so since its still pretty rough and not ready for mainstream use.

That said, I plan to add them when the time is right and before the CoreOS Container Linux deprecation. Stay tuned to project announcements and the changelog.
