### ISSUE TITLE
Allow VPC peering in AWS by add extra variable routes to the default routing table 

### ISSUE THREAD

**Issue by meabed** [poseidon/typhoon#649]
When creating new cluster, since it's not recommended to use shared VPC.
Its good option to peer VPC and allow networking. but every-time We extend the default routing table and apply again it remove the peer networking routes.
The proposed solution is to allow extra routes to the default routing table as variables passed to the module.
Would this make sense? I could open a PR if so :) Thanks!

Screen shot of terraform apply:
![image](https://user-images.githubusercontent.com/45731/75081300-17870980-5528-11ea-9a44-efd047d814bd.png)

**Comment by dghubble** [comment]
If you need to customize any internal resource (such as an `aws_route_table`), use Terraform data to reference and customize/extend that resource. You would not pass those customizations into the  Typhoon module. You can use Typhoon's outputs (e.g. `vpc_id`) to assist in referencing the [aws_route_table](https://www.terraform.io/docs/providers/aws/d/route_table.html).

**Comment by meabed** [comment]
Hi @dghubble - thanks for the suggestion, I have used terraform data to fetch the route table and modify it.
However the result was not idempotent, first time i apply, terraform add the routes, second time it removes the routes.
So when I passed the routes via variable the terraform apply was idempotent.
it would be great to accommodate this change, the alternative i had was downloading the module and override it like below screenshot.

![image](https://user-images.githubusercontent.com/45731/75101011-cb070100-55ef-11ea-93ac-65622148295c.png)

and override the default route table 

![image](https://user-images.githubusercontent.com/45731/75101015-d823f000-55ef-11ea-9fc1-bd59d1a1f115.png)

![image](https://user-images.githubusercontent.com/45731/75101018-e114c180-55ef-11ea-845d-2079ba92f0ca.png)

**Comment by dghubble** [comment]
https://github.com/poseidon/typhoon/pull/654 shows an example using the suggested approach. Previously, extension would cause a diff because of terraform-provider-aws's inline route vs route resource, but this is addressed. Overrides are not needed.

Note the warning: Internally connecting AWS clusters can reduce cross-cloud flexibility and inhibit blue-green cluster patterns. It is not a recommended architecture. Make sure you don't create a situation where two clusters rely on one another's specific setup / cloud.
