### ISSUE TITLE
Kubelet dying on error - root container [kubepods] doesn't exist

### ISSUE THREAD

**Issue by isehgu** [poseidon/typhoon#712]
### Environment

* Platform: bare-metal
* OS: fedora-coreos
* Release: 61557e89a66248f846250f0faa7dd5138f54f9f7

### Problem

Kubelets on 2 of our worker nodes would die, and get into this loop of dying/restarting with the following error: `Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist`

Reboot fixes it. But some would die again at some point later, thus getting into the same loop.

Eventually, we had to set the following kubelet parameters in order for kubelet to come up successfully.
`--cgroups-per-qos=false`
`--enforce-node-allocatable=""`

We got this workaround from this old [thread](https://github.com/kubernetes/kubernetes/issues/43704)

All of our worker nodes are on the same kernel. They might have all had this issue in the past where we simply rebooted them. We started digging into this issue when one worker node repeatedly ran into this within the last few days.

### Desired Behavior

Kubelet should be able to come up successfully.

### Steps to Reproduce

On the problematic worker node, if I remove those parameters and restart kubelet, it would get into this dying/restarting again with the same error.

**Comment by dghubble** [comment]
This was a known race in upstream [Kubernetes](https://github.com/kubernetes/kubernetes/issues/79046) QoS before Kubernetes v1.16.0. It hasn't been observed on our Fedora CoreOS clusters on any plaform since QoS was [enabled](https://github.com/poseidon/typhoon/commit/e8d586f3b3dd5d21e81c9881d23b6c28ef407664) September last year.

Please check you're on a recent Kubernetes and Fedora CoreOS version. If you can reproduce the issue after that, please provide the details of your digging.

**Comment by isehgu** [comment]
After i opened this issue, another node starting showing the same behavior, and I had to put the same workaround in there to prevent kubelet from failing. All of my worker nodes are on the same kernel. I know this should've gotten fixed already, which is why it's so puzzling. I've attached the kubelet snippet that shows from starting to dying. I am hoping to get some insight on what's going on.
[kubelet.log](https://github.com/poseidon/typhoon/files/4533614/kubelet.log)


```
uname -r
4.19.106-coreos
```

```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-13T18:06:54Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dghubble** [comment]
Looks like you're actually using CoreOS Container Linux (unknown version) and Kubernetes v1.17.4 (hyperkube). 

On CoreOS Container Linux clusters, the Kubelet has used QoS defaults from the very earliest releases. There have been no changes or observations of QoS cgroup issues on our CL clusters on any platform (including v1.17.4 on bare-metal, when it was the current version).

Given that, be sure CoreOS is updated, look into any modifications you may have made (e.g. cgroup driver), and remove any privileged workloads that could be mucking with docker or other settings, compare your nodes to determine how they differ. If it happens to existing nodes (rather than fresh nodes with no workloads), consider what recently ran on those. This is about the extent of the support advice I'll offer.

**Comment by lc9900** [comment]
Thanks @dghubble, much appreciated.
