### ISSUE TITLE
More then one ssh key

### ISSUE THREAD

**Issue by mleklund** [poseidon/typhoon#72]
### Feature

Make ssh_authorized_key, ssh_authorized_keys and allow a list of keys.  Our organization discourages shared keys.

### Tradeoffs

Unknown.

**Comment by dghubble** [comment]
Its not a Typhoon choice. Terraform file templating does not allow interpolation of lists or maps. https://github.com/hashicorp/terraform/issues/9368#issuecomment-315843340

If you really must have multiple keys, you have to use dirty workarounds like adding additional variables (e.g. `ssh_authorized_key_one`, `ssh_authorized_key_two`, etc). I haven't seen a workaround that is palatable to merge.

If you find a better approach, please open a PR.

**Comment by khrisrichardson** [comment]
@dghubble, would you accept a PR for switching from templating to the [ignition provider](https://github.com/terraform-providers/terraform-provider-ignition/blob/master/ignition/resource_ignition_user.go#L23-L28), which does accept a list?

**Comment by dghubble** [comment]
@khrisrichardson I appreciate the interest, but I would not. I've evaluated it.

Container Linux Configs from plain-old templates provides readability, while the terraform-provider-ct plugin provides config validations (not just format, but semantics). That Ignition provider (which is not supported by CoreOS) requires configs be rewritten in a Terraform schema, reduces readability, lacks the same validations, and introduce maintenance concerns (i.e. each Ignition addition has to be reflected in the Ignition provider, it becomes a dependency). I'm for using Terraform to describe infrastructure, but less favorable to replacing/rewriting existing configs (or DSLs) with Terraform variants that need to same level of care and attention. I also don't like that it models the Ignition schema (designed for machines), rather than the Container Linux schema (which we designed for humans to write). Overall, the tradeoffs aren't worth it imo, at this time, perhaps if things change.

**Comment by dghubble** [comment]
Neither `terraform-provider-ct` nor `terraform-provider-ignition` are ideal and both lack some important designs needed for customization and the future of Typhoon. I've had some plans in mind to redesign this (perhaps as a new project, perhaps in provider-ct), but likely won't get to it until spring 2018.

**Comment by khrisrichardson** [comment]
I figured you had given it some thought, which is why I asked instead of blindly submitting a PR. Really appreciate your attention to detail.
