### ISSUE TITLE
CoreOS AMI query is broken

### ISSUE THREAD

**Issue by beyondbill** [poseidon/typhoon#838]
**Description**

CoreOS AMI query returns no result.

**Steps to Reproduce**

Try creating a k8s cluster in AWS with Typhoon. It throws the following errors

```
Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/green.typhoon/aws/container-linux/kubernetes/ami.tf line 11, in data "aws_ami" "coreos":
  11: data "aws_ami" "coreos" {


Error: Your query returned no results. Please change your search criteria and try again.

  on .terraform/modules/green.typhoon/aws/container-linux/kubernetes/workers/ami.tf line 11, in data "aws_ami" "coreos":
  11: data "aws_ami" "coreos" {
```

**Environment**

* Platform: aws
* OS: container-linux
* Release: Typhoon v1.18.2
* Terraform: v0.12.29

**Possible Solution**

A quick search of `CoreOS-stable` in all public AMIs shows that most of the results owned by `679593333241`. None of the AMIs are owned by the owner hardcoded in Typhoon today. It probably recently deleted all `CoreOS-stable` AMIs. Updating `owners` filter to `["679593333241"]` will fix the issue. But I won't open a PR until the legitimacy of this owner is verified.

**Comment by dghubble** [comment]
Yes, CoreOS was deprecated in favor of Fedora CoreOS or Flatcar Linux in [v1.18.3](https://github.com/poseidon/typhoon/blob/master/CHANGES.md#v1183) (May). The CoreOS-specific code was left in order to give people as much time as possible to move.

But now that CoreOS has followed up on its [planned AMI deletion](https://coreos.com/os/eol/), the various references can be removed. Since they'll not longer be of use to anyone.

Those using Flatcar Linux would notice this reference (due to the way the AWS provider unconditionally requests) and need to update the reference.

**Comment by dghubble** [comment]
Thanks for the report.

For Flatcar Linx + AWS, you could use `343db5b578b2712753e706509dfd119e786fa018` or later from #839, other platforms shouldn't need a change.
