### ISSUE TITLE
why bootkube?

### ISSUE THREAD

**Issue by xiang90** [poseidon/typhoon#90]
From readme, it says in-place upgrades is non-goal. Then why bootkube or self hosted Kubernetes is needed? Why not just use systemd+containers to avoid complexity, and achieve the minimalism goal more?

Kubernetes control plane is designed to allow maintenance windows. With HA setup, the maintenance window can even be minimized. The worker plane is tricker, but it has nothing to do with bootkube anyway. I do not think in-place upgrades will bring anything significant anyway to typhoon's goal. So I wont worry about the future plan to put bootkube in here now.

**Comment by xiang90** [comment]
Another value is to be able to re-config the control plane easily in the post-installation phase through k8s tooling (kubectl).

But I found very little of value of it in practice. Every time I want to change configuration is due to a upgrade. Then I would just regenerate all configurations of control plane, and re-deploy anyway.

I would like to hear other advantages of self hosted or bootkube you found in practice. Thanks.

**Comment by dghubble** [comment]
In the last 2+ year years maintaining Matchbox reference clusters (of the static (i.e. systemd+containers), self-hosted, and rktnetes varieties) and until recently Tectonic, I have a few comments (static and rktnetes variants were killed off over time).

Typhoon uses bootkube for reasons beyond just self-hosted. First, bootkube is maintained as a kubernetes-incubator project. That means it gets contributions from various folks with different focuses, its considered in security disclosures and discussions upstream, and it establishes common ground with similar projects. Second, bootkube runs automated conformance tests and CNCF certification tests so its easy to spot breakages (Typhoon doesn't pay $$$ for that infra). Finally, its mutually beneficial for Typhoon to leverage the community's work on bootkube as a low level piece and likewise it has contributed to bootkube's direction.

I'll break down your other points:

* Yes, holistic in-place upgrades are a non-goal (speaking in terms of the whole infrastructure, architecture, cluster design, components, etc.). That doesn't preclude being able to update manifests. Self-hosted only concerns manifest updates (a piece of the puzzle). Its true you can sometimes update those pieces in-place, but Typhoon makes no guarantees. In normal operations, reprovisioning is advised.
* At a few key points in the last few years, it has been handy to reconfigure components with `kubectl` instead of the usual reprovisioning process. The kube-dns vulnerabilities came to mind. If nothing else, it gives end users the ability to blast out certain critical changes immediately if a proper reprovision would take too long.
* Typhoon uses bootkube, but doesn't strictly care that the cluster is self-hosted. There are a few failure scenarios you can encounter in self-hosted that cannot occur in static clusters and Typhoon may in future move in a more static direction. However, its way more mature than it was when I was running the first versions - those failure scenarios are adequately dealt with and there isn't an immediate reason to shift the architecture.

Overall, I'm not making an argument for self-hosted here. Typhoon uses bootkube mainly to leverage its maturity, community involvement, testing infrastructure, and mind-share. To the end user, the fact that a few control plane components are run as self-hosted pods is just an internal implementation detail. To the end user, they `terraform apply` and get a cluster, that's it.

Note: In future, I'd prefer we reserve issues for concrete actionable tasks or code issues and use the provided IRC for discussions like this.

**Comment by xiang90** [comment]
>  In future, I'd prefer we reserve issues for concrete actionable tasks or code issues and use the provided IRC for discussions like this.

quick reply: probably there should be a mailing list for discussion like this one. irc or other instant messaging is not good for searching, sharing or long term discussion I think.

I will reply on other points in the next couple of days.

**Comment by dghubble** [comment]
I think the answer above describes the current reasons for using bootkube, which was the original question.

I'm closing for now, but lemme know if there is something I missed.
