### ISSUE TITLE
failed to copy assets, bootkube does not start

### ISSUE THREAD

**Issue by fbarbeira** [poseidon/typhoon#99]
### Environment

* Platform: bare-metal
* OS: container-linux
* Terraform: 0.11.2
* Plugins: 

### Problem

The terraform apply exits with the following:

```
module.bare-metal-myk8s.null_resource.bootkube-start (remote-exec): mv: cannot move '/home/core/assets' to '/opt/bootkube/assets': Directory not empty
module.bare-metal-myk8s.null_resource.bootkube-start (remote-exec): Job for bootkube.service failed because the control process exited with error code.
module.bare-metal-myk8s.null_resource.bootkube-start (remote-exec): See "systemctl  status bootkube.service" and "journalctl  -xe" for details.
```

### Desired Behavior

The directory on the controller node should not exist. If I remove the directory '/opt/bootkube/assets' and run terraform apply again, then does the 'mv' but the service 'bootkube' does not start.

```
core@c1-k8s /opt $ sudo systemctl  status bootkube.service
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-01-17 13:44:42 UTC; 11min ago
  Process: 4871 ExecStart=/usr/bin/bash /opt/tectonic/bootkube.sh (code=exited, status=200/CHDIR)
 Main PID: 4871 (code=exited, status=200/CHDIR)
      CPU: 1ms

Jan 17 13:44:42 c1-k8s.server.com systemd[1]: Starting Bootstrap a Kubernetes cluster...
Jan 17 13:44:42 c1-k8s.server.com systemd[1]: bootkube.service: Main process exited, code=exited, status=200/CHD
Jan 17 13:44:42 c1-k8s.server.com systemd[1]: Failed to start Bootstrap a Kubernetes cluster.
Jan 17 13:44:42 c1-k8s.server.com systemd[1]: bootkube.service: Unit entered failed state.
Jan 17 13:44:42 c1-k8s.server.com systemd[1]: bootkube.service: Failed with result 'exit-code'.
core@c1-k8s /opt $
```

Furthermore, the directory '/opt/tectonic/' does not exist.

### Steps to Reproduce

Follow the steps of a bare-metal installation.

**Comment by dghubble** [comment]
Please show `bootkube.service` and compare with https://github.com/poseidon/typhoon/blob/master/bare-metal/container-linux/kubernetes/cl/controller.yaml.tmpl#L101.

Tectonic and `/opt/tectonic` are from a project by CoreOS. They do not appear anywhere in Typhoon. That controller is not a Typhoon controller. In cases where you see nodes that seem to be provisioned with the wrong contents consider:

* Are we talking to the right machine? When setting the controller domain(s), there are no typos or copy-pastes from another cluster? Do the names resolve to the right IP?
* If the reprovision wasn't network install failed for some reason and the machine fell back to booting from disk, would that explain the disk contents? Do the disk contents match the disk from the machine's prior life?

### Normal

When reprovisioning a set of machines (regardless of what they were), power them off, set their next boot device to PXE, `terraform apply` with the next cluster definition, and then power them on - they'll PXE boot, install to a disk, and reboot as a controller/worker. Covered [here](https://typhoon.psdn.io/topics/maintenance/#bare-metal)

### Debug Tips

If you still see the problem, watch the SOL console and be sure the PXE boot is actually occurring. It could be falling back to disk which would boot the node into whatever its role was before. You could also `dd` the beginning of the disk(s) to ensure they're not bootable (since you're planning on nuking that data anyway) - then you'd either see a successful PXE boot or failure to boot and be able to debug why.

**Comment by fbarbeira** [comment]
Ok, it was my fault. The nodes had a previous installation of a tectonic cluster. In the variables.tf file I forgot to specify the 8080 port on the matchbox service so the installation was not successfully.

Now it works fine. Sorry for the issue :)

**Comment by michas2** [comment]
Interesting, I just now ran into the same issue.

On a bare metal cluster I used to run tectonic. Now I used the typhoon terraform module to install typhoon on the same nodes. After a reboot from the typhoon provisioned matchbox service, I expected the typhoon installation to completely reinstall the nodes, but for some reason I still end up with the old tectonic installation. - I'm going to debug the reason further, but it's good to see that others stumbled into the same issue. :)

Maybe the final terraform check should verify that it indeed connects to a freshly installed typhoon cluster. (Instead it is (kind of) happy and tells "Apply complete".)

**Comment by dghubble** [comment]
The install to disk stage will retry to install to the desired disk over
and over. So if the coreos-install script was failing (e.g. some dm volumes
can trip up the script) you wouldn't see it reboot, it would just sit there
retrying and have sshd on 2222 in case you need to debug.

What's probably happening instead is that machine was just booted from the
existing old disk. It never PXE booted into the Typhoon disk install stage.
You can power it down, set it's next boot device to pxe, and use sol to
watch it come up. Tail Matchbox logs to ensure it's matching the right
profile.

Another possibility is that Tectonic has left state in Matchbox and it
still matches to that machine. With Typhoon, removing a cluster removes
state from Matchbox, but in Tectonic we didn't have a decent setup for that
(unless you knew exactly what to do with the assets bundle).

**Comment by michas2** [comment]
I now found the time to dig deeper into my issue and set up a new issue with all the detail at #326
